version: "3.8"
services:
  spring:
    container_name: spring
    image: "neptunes032/momelet_spring:latest"
    env_file:
      - ./env/spring.env
    ports:
    - 8080:8080
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3030:3000
    depends_on:
      - prometheus
volumes:
  prometheus_data:
  grafana_data:
